package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"time"

	graphql1 "github.com/secmon-lab/hecatoncheires/pkg/domain/model/graphql"
)

// SetFavoriteWorkspaces is the resolver for the setFavoriteWorkspaces field.
func (r *mutationResolver) SetFavoriteWorkspaces(ctx context.Context, workspaceIds []string) ([]string, error) {
	return r.UseCases.Dashboard.SetFavoriteWorkspaces(ctx, workspaceIds)
}

// MyOpenCases is the resolver for the myOpenCases field.
func (r *queryResolver) MyOpenCases(ctx context.Context) ([]*graphql1.MyOpenCase, error) {
	items, err := r.UseCases.Dashboard.ListMyOpenCases(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.MyOpenCase, len(items))
	for i, it := range items {
		result[i] = toGraphQLMyOpenCase(it)
	}
	return result, nil
}

// MyDueActions is the resolver for the myDueActions field.
func (r *queryResolver) MyDueActions(ctx context.Context) ([]*graphql1.MyDueAction, error) {
	items, err := r.UseCases.Dashboard.ListMyDueActions(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.MyDueAction, len(items))
	for i, it := range items {
		result[i] = toGraphQLMyDueAction(it)
	}
	return result, nil
}

// FavoriteWorkspaceIds is the resolver for the favoriteWorkspaceIds field.
func (r *queryResolver) FavoriteWorkspaceIds(ctx context.Context) ([]string, error) {
	return r.UseCases.Dashboard.GetFavoriteWorkspaces(ctx)
}

// HomeMessage is the resolver for the homeMessage field.
func (r *queryResolver) HomeMessage(ctx context.Context, clientTime time.Time, lang string) (*graphql1.HomeMessage, error) {
	msg, err := r.UseCases.Dashboard.GenerateHomeMessage(ctx, clientTime, lang)
	if err != nil {
		return nil, err
	}
	return &graphql1.HomeMessage{Message: msg}, nil
}
