package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"strings"

	goerr "github.com/m-mizutani/goerr/v2"
	"github.com/secmon-lab/hecatoncheires/pkg/domain/interfaces"
	"github.com/secmon-lab/hecatoncheires/pkg/domain/model"
	"github.com/secmon-lab/hecatoncheires/pkg/domain/model/auth"
	graphql1 "github.com/secmon-lab/hecatoncheires/pkg/domain/model/graphql"
	"github.com/secmon-lab/hecatoncheires/pkg/domain/types"
	"github.com/secmon-lab/hecatoncheires/pkg/usecase"
)

// Case is the resolver for the case field.
func (r *actionResolver) Case(ctx context.Context, obj *graphql1.Action) (*graphql1.Case, error) {
	loaders := GetDataLoaders(ctx)
	c, err := loaders.Case.Load(ctx, MakeCaseKey(obj.WorkspaceID, int64(obj.CaseID)))()
	if err != nil {
		return nil, err
	}
	if c == nil {
		return nil, nil
	}
	return toGraphQLCase(c, obj.WorkspaceID), nil
}

// Assignee is the resolver for the assignee field.
func (r *actionResolver) Assignee(ctx context.Context, obj *graphql1.Action) (*graphql1.SlackUser, error) {
	if obj.AssigneeID == nil || *obj.AssigneeID == "" {
		return nil, nil
	}
	loaders := GetDataLoaders(ctx)
	user, err := loaders.SlackUser.Load(ctx, *obj.AssigneeID)()
	if err != nil {
		return nil, err
	}
	// Missing assignee resolves to a nullable field on the Action - the
	// schema permits null here so we don't escalate to a field error
	// the way Case.Reporter does.
	return user, nil
}

// Messages is the resolver for the messages field.
func (r *actionResolver) Messages(ctx context.Context, obj *graphql1.Action, limit *int, cursor *string) (*graphql1.SlackMessageConnection, error) {
	empty := &graphql1.SlackMessageConnection{
		Items:      []*graphql1.SlackMessage{},
		NextCursor: "",
	}

	// Inherit access control from the parent Case: if the requester cannot
	// see the case, they cannot see the action's thread messages either.
	loaders := GetDataLoaders(ctx)
	c, err := loaders.Case.Load(ctx, MakeCaseKey(obj.WorkspaceID, int64(obj.CaseID)))()
	if err != nil {
		return nil, err
	}
	if c == nil || c.AccessDenied {
		return empty, nil
	}

	limitVal := 20
	if limit != nil && *limit > 0 {
		limitVal = *limit
	}
	cursorVal := ""
	if cursor != nil {
		cursorVal = *cursor
	}

	messages, nextCursor, err := r.repo.ActionMessage().List(ctx, obj.WorkspaceID, int64(obj.ID), limitVal, cursorVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list action messages from repository")
	}

	items := make([]*graphql1.SlackMessage, len(messages))
	for i, m := range messages {
		items[i] = toGraphQLSlackMessage(m)
	}
	return &graphql1.SlackMessageConnection{
		Items:      items,
		NextCursor: nextCursor,
	}, nil
}

// Events is the resolver for the events field.
func (r *actionResolver) Events(ctx context.Context, obj *graphql1.Action, limit *int, cursor *string) (*graphql1.ActionEventConnection, error) {
	empty := &graphql1.ActionEventConnection{
		Items:      []*graphql1.ActionEvent{},
		NextCursor: "",
	}

	loaders := GetDataLoaders(ctx)
	c, err := loaders.Case.Load(ctx, MakeCaseKey(obj.WorkspaceID, int64(obj.CaseID)))()
	if err != nil {
		return nil, err
	}
	if c == nil || c.AccessDenied {
		return empty, nil
	}

	limitVal := 50
	if limit != nil && *limit > 0 {
		limitVal = *limit
	}
	cursorVal := ""
	if cursor != nil {
		cursorVal = *cursor
	}

	events, nextCursor, err := r.repo.ActionEvent().List(ctx, obj.WorkspaceID, int64(obj.ID), limitVal, cursorVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list action events from repository")
	}

	items := make([]*graphql1.ActionEvent, len(events))
	for i, e := range events {
		items[i] = toGraphQLActionEvent(e)
	}
	return &graphql1.ActionEventConnection{
		Items:      items,
		NextCursor: nextCursor,
	}, nil
}

// Steps is the resolver for the steps field.
func (r *actionResolver) Steps(ctx context.Context, obj *graphql1.Action) ([]*graphql1.ActionStep, error) {
	empty := []*graphql1.ActionStep{}

	loaders := GetDataLoaders(ctx)
	c, err := loaders.Case.Load(ctx, MakeCaseKey(obj.WorkspaceID, int64(obj.CaseID)))()
	if err != nil {
		return nil, err
	}
	if c == nil || c.AccessDenied {
		return empty, nil
	}

	steps, err := r.UseCases.ActionStep.List(ctx, obj.WorkspaceID, int64(obj.ID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list action steps")
	}
	out := make([]*graphql1.ActionStep, 0, len(steps))
	for _, s := range steps {
		out = append(out, toGraphQLActionStep(s))
	}
	return out, nil
}

// StepProgress is the resolver for the stepProgress field.
func (r *actionResolver) StepProgress(ctx context.Context, obj *graphql1.Action) (*graphql1.ActionStepProgress, error) {
	zero := &graphql1.ActionStepProgress{Done: 0, Total: 0}

	loaders := GetDataLoaders(ctx)
	c, err := loaders.Case.Load(ctx, MakeCaseKey(obj.WorkspaceID, int64(obj.CaseID)))()
	if err != nil {
		return nil, err
	}
	if c == nil || c.AccessDenied {
		return zero, nil
	}

	done, total, err := r.UseCases.ActionStep.Progress(ctx, obj.WorkspaceID, int64(obj.ID))
	if err != nil {
		return nil, goerr.Wrap(err, "failed to compute action step progress")
	}
	return &graphql1.ActionStepProgress{Done: done, Total: total}, nil
}

// Actor is the resolver for the actor field.
func (r *actionEventResolver) Actor(ctx context.Context, obj *graphql1.ActionEvent) (*graphql1.SlackUser, error) {
	if obj.ActorID == "" {
		return nil, nil
	}
	loaders := GetDataLoaders(ctx)
	user, err := loaders.SlackUser.Load(ctx, obj.ActorID)()
	if err != nil {
		return nil, err
	}
	return user, nil
}

// ChannelUserCount is the resolver for the channelUserCount field.
func (r *caseResolver) ChannelUserCount(ctx context.Context, obj *graphql1.Case) (int, error) {
	return len(obj.ChannelUserIDs), nil
}

// ChannelUsers is the resolver for the channelUsers field.
func (r *caseResolver) ChannelUsers(ctx context.Context, obj *graphql1.Case, limit *int, offset *int, filter *string) (*graphql1.ChannelUserConnection, error) {
	if obj.AccessDenied || len(obj.ChannelUserIDs) == 0 {
		return &graphql1.ChannelUserConnection{
			Items:      []*graphql1.SlackUser{},
			TotalCount: 0,
			HasMore:    false,
		}, nil
	}

	// Resolve all channel user IDs to SlackUser via DataLoader (DB cache,
	// no Slack API). LoadMany returns one Result per key; nil entries
	// (missing repository rows) are filtered so the [SlackUser!]!
	// schema contract is honoured.
	loaders := GetDataLoaders(ctx)
	loaded, errs := loaders.SlackUser.LoadMany(ctx, obj.ChannelUserIDs)()
	for _, e := range errs {
		if e != nil {
			return nil, e
		}
	}
	allUsers := make([]*graphql1.SlackUser, 0, len(loaded))
	for _, u := range loaded {
		if u != nil {
			allUsers = append(allUsers, u)
		}
	}

	// Apply name filter if specified
	if filter != nil && *filter != "" {
		filterLower := strings.ToLower(*filter)
		filtered := make([]*graphql1.SlackUser, 0, len(allUsers))
		for _, u := range allUsers {
			if strings.Contains(strings.ToLower(u.Name), filterLower) ||
				strings.Contains(strings.ToLower(u.RealName), filterLower) {
				filtered = append(filtered, u)
			}
		}
		allUsers = filtered
	}

	total := len(allUsers)

	// Apply pagination
	defaultLimit := 50
	actualLimit := defaultLimit
	if limit != nil && *limit > 0 {
		actualLimit = *limit
	}
	actualOffset := 0
	if offset != nil && *offset > 0 {
		actualOffset = *offset
	}

	start := actualOffset
	if start > total {
		start = total
	}
	end := start + actualLimit
	if end > total {
		end = total
	}

	return &graphql1.ChannelUserConnection{
		Items:      allUsers[start:end],
		TotalCount: total,
		HasMore:    end < total,
	}, nil
}

// Reporter is the resolver for the reporter field.
func (r *caseResolver) Reporter(ctx context.Context, obj *graphql1.Case) (*graphql1.SlackUser, error) {
	if obj.ReporterID == nil || *obj.ReporterID == "" {
		return nil, nil
	}
	loaders := GetDataLoaders(ctx)
	user, err := loaders.SlackUser.Load(ctx, *obj.ReporterID)()
	if err != nil {
		return nil, err
	}
	// A reporter whose SlackUser is not in the repository (an unsynced
	// thread-mode poster, a deleted account, an ID that drifted, ...) resolves
	// to null rather than a field-level GraphQL error. The frontend prioritises
	// display: a single missing reporter must not fail the whole `cases` query
	// and blank out the list (see Sentry ARGUS-7S). Ops visibility is NOT lost
	// — the SlackUser dataloader reports every missing ID through
	// errutil.Handle (Sentry), so the gap is still surfaced to operators.
	return user, nil
}

// Assignees is the resolver for the assignees field.
func (r *caseResolver) Assignees(ctx context.Context, obj *graphql1.Case) ([]*graphql1.SlackUser, error) {
	if len(obj.AssigneeIDs) == 0 {
		return []*graphql1.SlackUser{}, nil
	}
	loaders := GetDataLoaders(ctx)
	loaded, errs := loaders.SlackUser.LoadMany(ctx, obj.AssigneeIDs)()
	for _, e := range errs {
		if e != nil {
			return nil, e
		}
	}
	// Drop nil entries: the schema declares assignees as
	// [SlackUser!]!, so nil elements would blow up GraphQL
	// marshalling for the whole list. The missing IDs were already
	// reported via errutil.Handle inside the batch function.
	result := make([]*graphql1.SlackUser, 0, len(loaded))
	for _, u := range loaded {
		if u != nil {
			result = append(result, u)
		}
	}
	return result, nil
}

// SlackChannelName is the resolver for the slackChannelName field.
func (r *caseResolver) SlackChannelName(ctx context.Context, obj *graphql1.Case) (*string, error) {
	if obj.SlackChannelID == nil || *obj.SlackChannelID == "" {
		return nil, nil
	}
	loaders := GetDataLoaders(ctx)
	return loaders.SlackChannelName.Load(ctx, *obj.SlackChannelID)()
}

// SlackChannelURL is the resolver for the slackChannelURL field.
func (r *caseResolver) SlackChannelURL(ctx context.Context, obj *graphql1.Case) (*string, error) {
	if obj.SlackChannelID == nil || *obj.SlackChannelID == "" {
		return nil, nil
	}
	slackSvc := r.UseCases.SlackService()
	if slackSvc == nil {
		return nil, nil
	}
	teamURL, err := slackSvc.GetTeamURL(ctx)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to get Slack team URL")
	}
	url := teamURL + "/archives/" + *obj.SlackChannelID
	return &url, nil
}

// Fields is the resolver for the fields field.
func (r *caseResolver) Fields(ctx context.Context, obj *graphql1.Case) ([]*graphql1.FieldValue, error) {
	if obj.AccessDenied {
		return []*graphql1.FieldValue{}, nil
	}
	// Field values are embedded in the Case and pre-populated by toGraphQLCase
	if obj.Fields == nil {
		return []*graphql1.FieldValue{}, nil
	}
	return obj.Fields, nil
}

// Actions is the resolver for the actions field.
func (r *caseResolver) Actions(ctx context.Context, obj *graphql1.Case, filter *graphql1.ActionArchiveFilter) ([]*graphql1.Action, error) {
	if obj.AccessDenied {
		return []*graphql1.Action{}, nil
	}

	scope := actionArchiveFilterToScope(filter)
	loaders := GetDataLoaders(ctx)
	loader := loaders.ActionsByCaseLoaderForScope(scope)
	actions, err := loader.Load(ctx, MakeActionsByCaseKey(obj.WorkspaceID, int64(obj.ID)))()
	if err != nil {
		return nil, err
	}

	// Convert domain Actions to GraphQL Actions
	result := make([]*graphql1.Action, len(actions))
	for i, a := range actions {
		result[i] = toGraphQLAction(a, obj.WorkspaceID)
	}
	return result, nil
}

// SlackMessages is the resolver for the slackMessages field.
func (r *caseResolver) SlackMessages(ctx context.Context, obj *graphql1.Case, limit *int, cursor *string) (*graphql1.SlackMessageConnection, error) {
	if obj.AccessDenied {
		return &graphql1.SlackMessageConnection{
			Items:      []*graphql1.SlackMessage{},
			NextCursor: "",
		}, nil
	}
	limitVal := 20
	if limit != nil && *limit > 0 {
		limitVal = *limit
	}
	cursorVal := ""
	if cursor != nil {
		cursorVal = *cursor
	}

	messages, nextCursor, err := r.repo.CaseMessage().List(ctx, obj.WorkspaceID, int64(obj.ID), limitVal, cursorVal)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to list case messages from repository")
	}

	items := make([]*graphql1.SlackMessage, len(messages))
	for i, m := range messages {
		items[i] = toGraphQLSlackMessage(m)
	}

	return &graphql1.SlackMessageConnection{
		Items:      items,
		NextCursor: nextCursor,
	}, nil
}

// AgentSources is the resolver for the agentSources field.
func (r *caseResolver) AgentSources(ctx context.Context, obj *graphql1.Case) ([]*graphql1.Source, error) {
	if obj == nil || obj.AccessDenied {
		return []*graphql1.Source{}, nil
	}
	if len(obj.AgentSourceIDs) == 0 {
		return []*graphql1.Source{}, nil
	}
	// Load all workspace sources once and filter by the Case's allowlist,
	// preserving the order the operator selected.
	sources, err := r.repo.Source().List(ctx, obj.WorkspaceID)
	if err != nil {
		return nil, goerr.Wrap(err, "list sources for case agent",
			goerr.V("workspace_id", obj.WorkspaceID),
			goerr.V("case_id", obj.ID))
	}
	known := make(map[model.SourceID]*model.Source, len(sources))
	for _, s := range sources {
		known[s.ID] = s
	}
	out := make([]*graphql1.Source, 0, len(obj.AgentSourceIDs))
	for _, raw := range obj.AgentSourceIDs {
		s, ok := known[model.SourceID(raw)]
		if !ok {
			// Source was deleted after selection — silently drop so the
			// page still renders; the operator can re-pick from the editor.
			continue
		}
		gq, err := toGraphQLSource(s)
		if err != nil {
			return nil, goerr.Wrap(err, "convert source for case agent",
				goerr.V("source_id", raw))
		}
		if gq != nil {
			out = append(out, gq)
		}
	}
	return out, nil
}

// Noop is the resolver for the noop field.
func (r *mutationResolver) Noop(ctx context.Context) (*bool, error) {
	result := true
	return &result, nil
}

// CreateCase is the resolver for the createCase field.
func (r *mutationResolver) CreateCase(ctx context.Context, workspaceID string, input graphql1.CreateCaseInput) (*graphql1.Case, error) {
	assigneeIDs := input.AssigneeIDs
	if assigneeIDs == nil {
		assigneeIDs = []string{}
	}

	fieldValues := toDomainFieldValues(input.Fields)

	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	isPrivate := input.IsPrivate != nil && *input.IsPrivate
	created, err := r.UseCases.Case.CreateCase(ctx, workspaceID, input.Title, description, assigneeIDs, fieldValues, isPrivate, "", "")
	if err != nil {
		return nil, err
	}

	return toGraphQLCase(created, workspaceID), nil
}

// UpdateCase is the resolver for the updateCase field.
func (r *mutationResolver) UpdateCase(ctx context.Context, workspaceID string, input graphql1.UpdateCaseInput) (*graphql1.Case, error) {
	patch := usecase.CaseUpdate{
		Title:       input.Title,
		Description: input.Description,
	}
	if input.AssigneeIDs != nil {
		patch.SetAssignees(input.AssigneeIDs)
	}
	if input.Fields != nil {
		patch.Fields = toDomainFieldValues(input.Fields)
	}

	updated, err := r.UseCases.Case.UpdateCase(ctx, workspaceID, int64(input.ID), patch)
	if err != nil {
		return nil, err
	}

	return toGraphQLCase(updated, workspaceID), nil
}

// DeleteCase is the resolver for the deleteCase field.
func (r *mutationResolver) DeleteCase(ctx context.Context, workspaceID string, id int) (bool, error) {
	if err := r.UseCases.Case.DeleteCase(ctx, workspaceID, int64(id)); err != nil {
		return false, err
	}
	return true, nil
}

// CloseCase is the resolver for the closeCase field.
func (r *mutationResolver) CloseCase(ctx context.Context, workspaceID string, id int) (*graphql1.Case, error) {
	closed, err := r.UseCases.Case.CloseCase(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(closed, workspaceID), nil
}

// ReopenCase is the resolver for the reopenCase field.
func (r *mutationResolver) ReopenCase(ctx context.Context, workspaceID string, id int) (*graphql1.Case, error) {
	reopened, err := r.UseCases.Case.ReopenCase(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(reopened, workspaceID), nil
}

// UpdateCaseStatus is the resolver for the updateCaseStatus field.
func (r *mutationResolver) UpdateCaseStatus(ctx context.Context, workspaceID string, input graphql1.UpdateCaseStatusInput) (*graphql1.Case, error) {
	updated, err := r.UseCases.Case.UpdateCaseStatus(ctx, workspaceID, int64(input.ID), input.Status)
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(updated, workspaceID), nil
}

// SyncCaseChannelUsers is the resolver for the syncCaseChannelUsers field.
func (r *mutationResolver) SyncCaseChannelUsers(ctx context.Context, workspaceID string, id int) (*graphql1.Case, error) {
	updated, err := r.UseCases.Case.SyncCaseChannelUsers(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(updated, workspaceID), nil
}

// CreateDraft is the resolver for the createDraft field.
func (r *mutationResolver) CreateDraft(ctx context.Context, workspaceID string, input graphql1.CreateDraftInput) (*graphql1.Case, error) {
	assigneeIDs := input.AssigneeIDs
	if assigneeIDs == nil {
		assigneeIDs = []string{}
	}
	fieldValues := toDomainFieldValues(input.Fields)

	title := ""
	if input.Title != nil {
		title = *input.Title
	}
	description := ""
	if input.Description != nil {
		description = *input.Description
	}
	isPrivate := input.IsPrivate != nil && *input.IsPrivate

	created, err := r.UseCases.Case.CreateDraft(ctx, workspaceID, title, description, assigneeIDs, fieldValues, isPrivate)
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(created, workspaceID), nil
}

// SubmitDraft is the resolver for the submitDraft field.
func (r *mutationResolver) SubmitDraft(ctx context.Context, workspaceID string, id int, input *graphql1.SubmitDraftInput) (*graphql1.Case, error) {
	var patch *usecase.CaseUpdate
	if input != nil {
		p := usecase.CaseUpdate{}
		if input.Title != nil {
			p.Title = input.Title
		}
		if input.Description != nil {
			p.Description = input.Description
		}
		if input.AssigneeIDs != nil {
			p.SetAssignees(input.AssigneeIDs)
		}
		if input.Fields != nil {
			p.Fields = toDomainFieldValues(input.Fields)
		}
		patch = &p
	}
	submitted, err := r.UseCases.Case.SubmitDraft(ctx, workspaceID, int64(id), patch)
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(submitted, workspaceID), nil
}

// DiscardDraft is the resolver for the discardDraft field.
func (r *mutationResolver) DiscardDraft(ctx context.Context, workspaceID string, id int) (bool, error) {
	if err := r.UseCases.Case.DiscardDraft(ctx, workspaceID, int64(id)); err != nil {
		return false, err
	}
	return true, nil
}

// CreateAction is the resolver for the createAction field.
func (r *mutationResolver) CreateAction(ctx context.Context, workspaceID string, input graphql1.CreateActionInput) (*graphql1.Action, error) {
	assigneeID := ""
	if input.AssigneeID != nil {
		assigneeID = *input.AssigneeID
	}

	slackMessageTS := ""
	if input.SlackMessageTs != nil {
		slackMessageTS = *input.SlackMessageTs
	}

	// Empty status lets the usecase substitute the workspace's initial id.
	var status types.ActionStatus
	if input.Status != nil {
		status = types.ActionStatus(*input.Status)
	}

	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	created, err := r.UseCases.Action.CreateAction(ctx, workspaceID, int64(input.CaseID), input.Title, description, assigneeID, slackMessageTS, status, input.DueDate)
	if err != nil {
		return nil, err
	}

	return toGraphQLAction(created, workspaceID), nil
}

// UpdateAction is the resolver for the updateAction field.
func (r *mutationResolver) UpdateAction(ctx context.Context, workspaceID string, input graphql1.UpdateActionInput) (*graphql1.Action, error) {
	var caseID *int64
	if input.CaseID != nil {
		id := int64(*input.CaseID)
		caseID = &id
	}

	var slackMessageTS *string
	if input.SlackMessageTs != nil {
		slackMessageTS = input.SlackMessageTs
	}

	var status *types.ActionStatus
	if input.Status != nil {
		s := types.ActionStatus(*input.Status)
		status = &s
	}

	clearDueDate := false
	if input.ClearDueDate != nil {
		clearDueDate = *input.ClearDueDate
	}

	clearAssignee := false
	if input.ClearAssignee != nil {
		clearAssignee = *input.ClearAssignee
	}

	actor := usecase.ActorRef{Kind: usecase.ActorKindSystem}
	if token, tokenErr := auth.TokenFromContext(ctx); tokenErr == nil {
		actor = usecase.ActorRef{Kind: usecase.ActorKindSlackUser, ID: token.Sub}
	}

	updated, err := r.UseCases.Action.UpdateAction(ctx, workspaceID, usecase.UpdateActionInput{
		ID:             int64(input.ID),
		CaseID:         caseID,
		Title:          input.Title,
		Description:    input.Description,
		AssigneeID:     input.AssigneeID,
		SlackMessageTS: slackMessageTS,
		Status:         status,
		DueDate:        input.DueDate,
		ClearDueDate:   clearDueDate,
		ClearAssignee:  clearAssignee,
		SlackSync:      usecase.SlackSyncFull,
		Actor:          actor,
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLAction(updated, workspaceID), nil
}

// ArchiveAction is the resolver for the archiveAction field.
//
// GraphQL is an externally exposed transport, so the resolver must always
// have an authenticated user. Falling back to ActorKindSystem here would let
// any unauthenticated request that slipped past the auth middleware bypass
// the private-case access check inside ArchiveAction's usecase. System-level
// archive flows go through the agent-tool adapter, never through GraphQL.
func (r *mutationResolver) ArchiveAction(ctx context.Context, workspaceID string, id int) (*graphql1.Action, error) {
	token, err := auth.TokenFromContext(ctx)
	if err != nil {
		return nil, err
	}
	actor := usecase.ActorRef{Kind: usecase.ActorKindSlackUser, ID: token.Sub}
	updated, archiveErr := r.UseCases.Action.ArchiveAction(ctx, workspaceID, int64(id), actor)
	if archiveErr != nil {
		return nil, archiveErr
	}
	return toGraphQLAction(updated, workspaceID), nil
}

// UnarchiveAction is the resolver for the unarchiveAction field.
//
// Mirrors ArchiveAction's auth requirement: a missing token is treated as a
// hard error rather than a silent fallback to system actor.
func (r *mutationResolver) UnarchiveAction(ctx context.Context, workspaceID string, id int) (*graphql1.Action, error) {
	token, err := auth.TokenFromContext(ctx)
	if err != nil {
		return nil, err
	}
	actor := usecase.ActorRef{Kind: usecase.ActorKindSlackUser, ID: token.Sub}
	updated, unarchiveErr := r.UseCases.Action.UnarchiveAction(ctx, workspaceID, int64(id), actor)
	if unarchiveErr != nil {
		return nil, unarchiveErr
	}
	return toGraphQLAction(updated, workspaceID), nil
}

// PostActionSlackMessage is the resolver for the postActionSlackMessage field.
func (r *mutationResolver) PostActionSlackMessage(ctx context.Context, workspaceID string, id int) (*graphql1.Action, error) {
	updated, err := r.UseCases.Action.PostSlackMessageToAction(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLAction(updated, workspaceID), nil
}

// AddActionStep is the resolver for the addActionStep field.
func (r *mutationResolver) AddActionStep(ctx context.Context, workspaceID string, input graphql1.AddActionStepInput) (*graphql1.ActionStep, error) {
	step, err := r.UseCases.ActionStep.Add(ctx, usecase.AddActionStepInput{
		WorkspaceID: workspaceID,
		ActionID:    int64(input.ActionID),
		Title:       input.Title,
		Actor:       resolveStepActor(ctx),
	})
	if err != nil {
		return nil, err
	}
	return toGraphQLActionStep(step), nil
}

// SetActionStepDone is the resolver for the setActionStepDone field.
func (r *mutationResolver) SetActionStepDone(ctx context.Context, workspaceID string, input graphql1.SetActionStepDoneInput) (*graphql1.ActionStep, error) {
	step, err := r.UseCases.ActionStep.SetDone(ctx, usecase.SetActionStepDoneInput{
		WorkspaceID: workspaceID,
		ActionID:    int64(input.ActionID),
		StepID:      input.StepID,
		Done:        input.Done,
		Actor:       resolveStepActor(ctx),
	})
	if err != nil {
		return nil, err
	}
	return toGraphQLActionStep(step), nil
}

// RenameActionStep is the resolver for the renameActionStep field.
func (r *mutationResolver) RenameActionStep(ctx context.Context, workspaceID string, input graphql1.RenameActionStepInput) (*graphql1.ActionStep, error) {
	step, err := r.UseCases.ActionStep.Rename(ctx, usecase.RenameActionStepInput{
		WorkspaceID: workspaceID,
		ActionID:    int64(input.ActionID),
		StepID:      input.StepID,
		Title:       input.Title,
		Actor:       resolveStepActor(ctx),
	})
	if err != nil {
		return nil, err
	}
	return toGraphQLActionStep(step), nil
}

// DeleteActionStep is the resolver for the deleteActionStep field.
func (r *mutationResolver) DeleteActionStep(ctx context.Context, workspaceID string, input graphql1.DeleteActionStepInput) (bool, error) {
	if err := r.UseCases.ActionStep.Delete(ctx, usecase.DeleteActionStepInput{
		WorkspaceID: workspaceID,
		ActionID:    int64(input.ActionID),
		StepID:      input.StepID,
		Actor:       resolveStepActor(ctx),
	}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateNotionDBSource is the resolver for the createNotionDBSource field.
func (r *mutationResolver) CreateNotionDBSource(ctx context.Context, workspaceID string, input graphql1.CreateNotionDBSourceInput) (*graphql1.Source, error) {
	created, err := r.UseCases.Source.CreateNotionDBSource(ctx, workspaceID, toUseCaseCreateNotionDBSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(created)
}

// CreateNotionPageSource is the resolver for the createNotionPageSource field.
func (r *mutationResolver) CreateNotionPageSource(ctx context.Context, workspaceID string, input graphql1.CreateNotionPageSourceInput) (*graphql1.Source, error) {
	created, err := r.UseCases.Source.CreateNotionPageSource(ctx, workspaceID, toUseCaseCreateNotionPageSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(created)
}

// CreateSlackSource is the resolver for the createSlackSource field.
func (r *mutationResolver) CreateSlackSource(ctx context.Context, workspaceID string, input graphql1.CreateSlackSourceInput) (*graphql1.Source, error) {
	created, err := r.UseCases.Source.CreateSlackSource(ctx, workspaceID, toUseCaseCreateSlackSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(created)
}

// CreateGitHubSource is the resolver for the createGitHubSource field.
func (r *mutationResolver) CreateGitHubSource(ctx context.Context, workspaceID string, input graphql1.CreateGitHubSourceInput) (*graphql1.Source, error) {
	created, err := r.UseCases.Source.CreateGitHubSource(ctx, workspaceID, toUseCaseCreateGitHubSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(created)
}

// UpdateSource is the resolver for the updateSource field.
func (r *mutationResolver) UpdateSource(ctx context.Context, workspaceID string, input graphql1.UpdateSourceInput) (*graphql1.Source, error) {
	updated, err := r.UseCases.Source.UpdateSource(ctx, workspaceID, toUseCaseUpdateSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(updated)
}

// UpdateSlackSource is the resolver for the updateSlackSource field.
func (r *mutationResolver) UpdateSlackSource(ctx context.Context, workspaceID string, input graphql1.UpdateSlackSourceInput) (*graphql1.Source, error) {
	updated, err := r.UseCases.Source.UpdateSlackSource(ctx, workspaceID, toUseCaseUpdateSlackSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(updated)
}

// UpdateGitHubSource is the resolver for the updateGitHubSource field.
func (r *mutationResolver) UpdateGitHubSource(ctx context.Context, workspaceID string, input graphql1.UpdateGitHubSourceInput) (*graphql1.Source, error) {
	updated, err := r.UseCases.Source.UpdateGitHubSource(ctx, workspaceID, toUseCaseUpdateGitHubSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(updated)
}

// UpdateNotionDBSource is the resolver for the updateNotionDBSource field.
func (r *mutationResolver) UpdateNotionDBSource(ctx context.Context, workspaceID string, input graphql1.UpdateNotionDBSourceInput) (*graphql1.Source, error) {
	updated, err := r.UseCases.Source.UpdateNotionDBSource(ctx, workspaceID, toUseCaseUpdateNotionDBSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(updated)
}

// UpdateNotionPageSource is the resolver for the updateNotionPageSource field.
func (r *mutationResolver) UpdateNotionPageSource(ctx context.Context, workspaceID string, input graphql1.UpdateNotionPageSourceInput) (*graphql1.Source, error) {
	updated, err := r.UseCases.Source.UpdateNotionPageSource(ctx, workspaceID, toUseCaseUpdateNotionPageSourceInput(input))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(updated)
}

// DeleteSource is the resolver for the deleteSource field.
func (r *mutationResolver) DeleteSource(ctx context.Context, workspaceID string, id string) (bool, error) {
	if err := r.UseCases.Source.DeleteSource(ctx, workspaceID, model.SourceID(id)); err != nil {
		return false, err
	}
	return true, nil
}

// ValidateNotionDb is the resolver for the validateNotionDB field.
func (r *mutationResolver) ValidateNotionDb(ctx context.Context, workspaceID string, databaseID string) (*graphql1.NotionDBValidationResult, error) {
	result, err := r.UseCases.Source.ValidateNotionDB(ctx, databaseID)
	if err != nil {
		return nil, err
	}

	gql := &graphql1.NotionDBValidationResult{
		Valid: result.Valid,
	}
	if result.DatabaseTitle != "" {
		gql.DatabaseTitle = &result.DatabaseTitle
	}
	if result.DatabaseURL != "" {
		gql.DatabaseURL = &result.DatabaseURL
	}
	if result.ErrorMessage != "" {
		gql.ErrorMessage = &result.ErrorMessage
	}

	return gql, nil
}

// ValidateNotionPage is the resolver for the validateNotionPage field.
func (r *mutationResolver) ValidateNotionPage(ctx context.Context, workspaceID string, pageID string) (*graphql1.NotionPageValidationResult, error) {
	result, err := r.UseCases.Source.ValidateNotionPage(ctx, pageID)
	if err != nil {
		return nil, err
	}

	gql := &graphql1.NotionPageValidationResult{
		Valid: result.Valid,
	}
	if result.PageTitle != "" {
		gql.PageTitle = &result.PageTitle
	}
	if result.PageURL != "" {
		gql.PageURL = &result.PageURL
	}
	if result.ErrorMessage != "" {
		gql.ErrorMessage = &result.ErrorMessage
	}

	return gql, nil
}

// UpdateCaseAgentSettings is the resolver for the updateCaseAgentSettings field.
func (r *mutationResolver) UpdateCaseAgentSettings(ctx context.Context, workspaceID string, input graphql1.UpdateCaseAgentSettingsInput) (*graphql1.Case, error) {
	ids := make([]model.SourceID, 0, len(input.EnabledSourceIds))
	for _, raw := range input.EnabledSourceIds {
		ids = append(ids, model.SourceID(raw))
	}
	updated, err := r.UseCases.Case.UpdateAgentSettings(ctx, workspaceID, int64(input.CaseID), input.AgentAdditionalPrompt, ids)
	if err != nil {
		return nil, err
	}
	return toGraphQLCase(updated, workspaceID), nil
}

// CreateCaseImport is the resolver for the createCaseImport field.
func (r *mutationResolver) CreateCaseImport(ctx context.Context, workspaceID string, input graphql1.CreateCaseImportInput) (*graphql1.ImportSession, error) {
	originalFileName := ""
	if input.OriginalFileName != nil {
		originalFileName = *input.OriginalFileName
	}
	session, err := r.UseCases.Import.Create(ctx, workspaceID, input.Content, originalFileName)
	if err != nil {
		return nil, err
	}
	return toGraphQLImportSession(ctx, r.repo, r.UseCases.WorkspaceRegistry(), session), nil
}

// ExecuteCaseImport is the resolver for the executeCaseImport field.
func (r *mutationResolver) ExecuteCaseImport(ctx context.Context, workspaceID string, id string) (*graphql1.ImportSession, error) {
	session, err := r.UseCases.Import.Execute(ctx, workspaceID, model.ImportSessionID(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLImportSession(ctx, r.repo, r.UseCases.WorkspaceRegistry(), session), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, workspaceID string) (*graphql1.Workspace, error) {
	entry, err := r.UseCases.WorkspaceRegistry().Get(workspaceID)
	if err != nil {
		return nil, err
	}
	return &graphql1.Workspace{
		ID:   entry.Workspace.ID,
		Name: entry.Workspace.Name,
	}, nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]*graphql1.Workspace, error) {
	entries := r.UseCases.WorkspaceRegistry().List()
	result := make([]*graphql1.Workspace, len(entries))
	for i, entry := range entries {
		result[i] = &graphql1.Workspace{
			ID:   entry.Workspace.ID,
			Name: entry.Workspace.Name,
		}
	}
	return result, nil
}

// Cases is the resolver for the cases field.
func (r *queryResolver) Cases(ctx context.Context, workspaceID string, status *types.CaseStatus) ([]*graphql1.Case, error) {
	cases, err := r.UseCases.Case.ListCases(ctx, workspaceID, status)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.Case, len(cases))
	for i, c := range cases {
		result[i] = toGraphQLCase(c, workspaceID)
	}

	return result, nil
}

// Case is the resolver for the case field.
func (r *queryResolver) Case(ctx context.Context, workspaceID string, id int) (*graphql1.Case, error) {
	c, err := r.UseCases.Case.GetCase(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}

	return toGraphQLCase(c, workspaceID), nil
}

// Drafts is the resolver for the drafts field.
func (r *queryResolver) Drafts(ctx context.Context, workspaceID string) ([]*graphql1.Case, error) {
	drafts, err := r.UseCases.Case.ListDrafts(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.Case, len(drafts))
	for i, c := range drafts {
		result[i] = toGraphQLCase(c, workspaceID)
	}
	return result, nil
}

// Actions is the resolver for the actions field.
func (r *queryResolver) Actions(ctx context.Context, workspaceID string, filter *graphql1.ActionArchiveFilter) ([]*graphql1.Action, error) {
	opts := interfaces.ActionListOptions{ArchiveScope: actionArchiveFilterToScope(filter)}
	actions, err := r.UseCases.Action.ListActions(ctx, workspaceID, opts)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.Action, len(actions))
	for i, a := range actions {
		result[i] = toGraphQLAction(a, workspaceID)
	}

	return result, nil
}

// Action is the resolver for the action field.
func (r *queryResolver) Action(ctx context.Context, workspaceID string, id int) (*graphql1.Action, error) {
	a, err := r.UseCases.Action.GetAction(ctx, workspaceID, int64(id))
	if err != nil {
		return nil, err
	}

	return toGraphQLAction(a, workspaceID), nil
}

// ActionsByCase is the resolver for the actionsByCase field.
func (r *queryResolver) ActionsByCase(ctx context.Context, workspaceID string, caseID int, filter *graphql1.ActionArchiveFilter) ([]*graphql1.Action, error) {
	opts := interfaces.ActionListOptions{ArchiveScope: actionArchiveFilterToScope(filter)}
	actions, err := r.UseCases.Action.GetActionsByCase(ctx, workspaceID, int64(caseID), opts)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.Action, len(actions))
	for i, a := range actions {
		result[i] = toGraphQLAction(a, workspaceID)
	}

	return result, nil
}

// OpenCaseActions is the resolver for the openCaseActions field.
func (r *queryResolver) OpenCaseActions(ctx context.Context, workspaceID string) ([]*graphql1.Action, error) {
	actions, err := r.UseCases.Action.ListOpenCaseActions(ctx, workspaceID)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.Action, len(actions))
	for i, a := range actions {
		result[i] = toGraphQLAction(a, workspaceID)
	}

	return result, nil
}

// FieldConfiguration is the resolver for the fieldConfiguration field.
func (r *queryResolver) FieldConfiguration(ctx context.Context, workspaceID string) (*graphql1.FieldConfiguration, error) {
	schema := r.UseCases.Case.GetFieldConfiguration(workspaceID)

	fields := make([]*graphql1.FieldDefinition, len(schema.Fields))
	for i, field := range schema.Fields {
		options := make([]*graphql1.FieldOption, len(field.Options))
		for j, opt := range field.Options {
			metadata := opt.Metadata
			if metadata == nil {
				metadata = make(map[string]any)
			}
			metadataJSON, _ := json.Marshal(metadata)
			metadataStr := string(metadataJSON)

			options[j] = &graphql1.FieldOption{
				ID:          opt.ID,
				Name:        opt.Name,
				Description: &field.Options[j].Description,
				Metadata:    &metadataStr,
			}
		}

		fieldType := toGraphQLFieldType(field.Type)

		fields[i] = &graphql1.FieldDefinition{
			ID:          field.ID,
			Name:        field.Name,
			Type:        fieldType,
			Required:    field.Required,
			Description: &field.Description,
			Options:     options,
		}
	}

	statusSet := r.UseCases.Case.GetActionStatusSet(workspaceID)

	return &graphql1.FieldConfiguration{
		Fields: fields,
		Labels: &graphql1.EntityLabels{
			Case: schema.Labels.Case,
		},
		ActionConfig: toActionConfig(statusSet),
	}, nil
}

// CaseStatusConfig is the resolver for the caseStatusConfig field.
func (r *queryResolver) CaseStatusConfig(ctx context.Context, workspaceID string) (*graphql1.ActionConfig, error) {
	statusSet := r.UseCases.Case.GetCaseStatusSet(workspaceID)
	if statusSet == nil {
		// Channel-mode workspace: no Case status set. Null is the schema
		// contract for "this workspace does not use Case-level statuses".
		return nil, nil
	}
	return toActionConfig(statusSet), nil
}

// SlackUsers is the resolver for the slackUsers field.
func (r *queryResolver) SlackUsers(ctx context.Context) ([]*graphql1.SlackUser, error) {
	users, err := r.repo.SlackUser().GetAll(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.SlackUser, len(users))
	for i, u := range users {
		var imageURL *string
		if u.ImageURL != "" {
			url := u.ImageURL
			imageURL = &url
		}
		result[i] = &graphql1.SlackUser{
			ID:       string(u.ID),
			Name:     u.Name,
			RealName: u.RealName,
			ImageURL: imageURL,
		}
	}

	return result, nil
}

// SlackJoinedChannels is the resolver for the slackJoinedChannels field.
func (r *queryResolver) SlackJoinedChannels(ctx context.Context) ([]*graphql1.SlackChannelInfo, error) {
	channels, err := r.UseCases.Source.ListSlackChannels(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.SlackChannelInfo, len(channels))
	for i, ch := range channels {
		result[i] = &graphql1.SlackChannelInfo{
			ID:   ch.ID,
			Name: ch.Name,
		}
	}

	return result, nil
}

// Sources is the resolver for the sources field.
func (r *queryResolver) Sources(ctx context.Context, workspaceID string) ([]*graphql1.Source, error) {
	sources, err := r.UseCases.Source.ListSources(ctx, workspaceID)
	if err != nil {
		return nil, err
	}

	result := make([]*graphql1.Source, 0, len(sources))
	for _, s := range sources {
		gql, err := toGraphQLSource(s)
		if err != nil {
			return nil, err
		}
		result = append(result, gql)
	}

	return result, nil
}

// Source is the resolver for the source field.
func (r *queryResolver) Source(ctx context.Context, workspaceID string, id string) (*graphql1.Source, error) {
	source, err := r.UseCases.Source.GetSource(ctx, workspaceID, model.SourceID(id))
	if err != nil {
		return nil, err
	}

	return toGraphQLSource(source)
}

// ValidateGitHubRepo is the resolver for the validateGitHubRepo field.
func (r *queryResolver) ValidateGitHubRepo(ctx context.Context, workspaceID string, repository string) (*graphql1.GitHubRepoValidationResult, error) {
	result, err := r.UseCases.Source.ValidateGitHubRepo(ctx, repository)
	if err != nil {
		return nil, err
	}

	gql := &graphql1.GitHubRepoValidationResult{
		Valid:                result.Valid,
		CanFetchPullRequests: result.CanFetchPullRequests,
		CanFetchIssues:       result.CanFetchIssues,
	}
	if result.Owner != "" {
		gql.Owner = &result.Owner
	}
	if result.Repo != "" {
		gql.Repo = &result.Repo
	}
	if result.FullName != "" {
		gql.FullName = &result.FullName
	}
	if result.Description != "" {
		gql.Description = &result.Description
	}
	if result.IsPrivate {
		gql.IsPrivate = &result.IsPrivate
	}
	if result.PullRequestCount > 0 {
		gql.PullRequestCount = &result.PullRequestCount
	}
	if result.IssueCount > 0 {
		gql.IssueCount = &result.IssueCount
	}
	if result.ErrorMessage != "" {
		gql.ErrorMessage = &result.ErrorMessage
	}

	return gql, nil
}

// AssistLogs is the resolver for the assistLogs field.
func (r *queryResolver) AssistLogs(ctx context.Context, workspaceID string, caseID int, limit *int, offset *int) (*graphql1.AssistLogConnection, error) {
	// Access control: check parent case
	parentCase, caseErr := r.repo.Case().Get(ctx, workspaceID, int64(caseID))
	if caseErr == nil {
		token, tokenErr := auth.TokenFromContext(ctx)
		if tokenErr == nil && !model.IsCaseAccessible(parentCase, token.Sub) {
			return &graphql1.AssistLogConnection{
				Items:      []*graphql1.AssistLog{},
				TotalCount: 0,
				HasMore:    false,
			}, nil
		}
	}

	limitVal := 20
	if limit != nil && *limit > 0 {
		limitVal = *limit
	}
	if limitVal > 50 {
		limitVal = 50
	}

	offsetVal := 0
	if offset != nil && *offset > 0 {
		offsetVal = *offset
	}

	logs, totalCount, err := r.repo.AssistLog().List(ctx, workspaceID, int64(caseID), limitVal, offsetVal)
	if err != nil {
		return nil, err
	}

	items := make([]*graphql1.AssistLog, len(logs))
	for i, l := range logs {
		items[i] = &graphql1.AssistLog{
			ID:        string(l.ID),
			CaseID:    int(l.CaseID),
			Summary:   l.Summary,
			Actions:   l.Actions,
			Reasoning: l.Reasoning,
			NextSteps: l.NextSteps,
			CreatedAt: l.CreatedAt,
		}
	}

	hasMore := (offsetVal + len(logs)) < totalCount

	return &graphql1.AssistLogConnection{
		Items:      items,
		TotalCount: totalCount,
		HasMore:    hasMore,
	}, nil
}

// CaseJobRunLogs is the resolver for the caseJobRunLogs field.
func (r *queryResolver) CaseJobRunLogs(ctx context.Context, workspaceID string, caseID int, first *int, after *string) (*graphql1.JobRunLogConnection, error) {
	page := 0
	if first != nil {
		page = *first
	}
	result, err := r.UseCases.JobRun.ListLogsByCase(ctx, workspaceID, int64(caseID), page, after)
	if err != nil {
		return nil, err
	}
	items := make([]*graphql1.JobRunLog, 0, len(result.Items))
	for _, log := range result.Items {
		items = append(items, toGraphQLJobRunLog(log, r.UseCases.JobRun.ResolveJobName(workspaceID, log.JobID)))
	}
	return &graphql1.JobRunLogConnection{
		Items:      items,
		NextCursor: result.NextCursor,
	}, nil
}

// JobRunLog is the resolver for the jobRunLog field.
func (r *queryResolver) JobRunLog(ctx context.Context, workspaceID string, caseID int, runID string) (*graphql1.JobRunLog, error) {
	log, err := r.UseCases.JobRun.GetLog(ctx, workspaceID, int64(caseID), runID)
	if err != nil {
		return nil, err
	}
	return toGraphQLJobRunLog(log, r.UseCases.JobRun.ResolveJobName(workspaceID, log.JobID)), nil
}

// JobRunEvents is the resolver for the jobRunEvents field.
func (r *queryResolver) JobRunEvents(ctx context.Context, workspaceID string, caseID int, runID string) ([]*graphql1.JobRunEvent, error) {
	events, err := r.UseCases.JobRun.ListEvents(ctx, workspaceID, int64(caseID), runID)
	if err != nil {
		return nil, err
	}
	out := make([]*graphql1.JobRunEvent, 0, len(events))
	for _, ev := range events {
		gq, err := toGraphQLJobRunEvent(ev)
		if err != nil {
			return nil, err
		}
		out = append(out, gq)
	}
	return out, nil
}

// CaseImport is the resolver for the caseImport field.
func (r *queryResolver) CaseImport(ctx context.Context, workspaceID string, id string) (*graphql1.ImportSession, error) {
	session, err := r.UseCases.Import.Get(ctx, workspaceID, model.ImportSessionID(id))
	if err != nil {
		return nil, err
	}
	return toGraphQLImportSession(ctx, r.repo, r.UseCases.WorkspaceRegistry(), session), nil
}

// Action returns ActionResolver implementation.
func (r *Resolver) Action() ActionResolver { return &actionResolver{r} }

// ActionEvent returns ActionEventResolver implementation.
func (r *Resolver) ActionEvent() ActionEventResolver { return &actionEventResolver{r} }

// Case returns CaseResolver implementation.
func (r *Resolver) Case() CaseResolver { return &caseResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type actionResolver struct{ *Resolver }
type actionEventResolver struct{ *Resolver }
type caseResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *caseResolver) SlackThreadTs(ctx context.Context, obj *graphql1.Case) (*string, error) {
	panic(fmt.Errorf("not implemented: SlackThreadTs - slackThreadTS"))
}
func (r *caseResolver) IsThreadBound(ctx context.Context, obj *graphql1.Case) (bool, error) {
	panic(fmt.Errorf("not implemented: IsThreadBound - isThreadBound"))
}
func (r *caseResolver) BoardStatus(ctx context.Context, obj *graphql1.Case) (*string, error) {
	panic(fmt.Errorf("not implemented: BoardStatus - boardStatus"))
}
*/
