package graphql

import (
	"github.com/m-mizutani/goerr/v2"
	"github.com/secmon-lab/hecatoncheires/pkg/domain/model"
	graphql1 "github.com/secmon-lab/hecatoncheires/pkg/domain/model/graphql"
	"github.com/secmon-lab/hecatoncheires/pkg/usecase"
)

// toGraphQLSource converts domain Source to GraphQL Source
func toGraphQLSource(source *model.Source) (*graphql1.Source, error) {
	if source == nil {
		return nil, nil
	}

	sourceType, err := toGraphQLSourceType(source.SourceType)
	if err != nil {
		return nil, err
	}

	gqlSource := &graphql1.Source{
		ID:          string(source.ID),
		Name:        source.Name,
		SourceType:  sourceType,
		Description: source.Description,
		Enabled:     source.Enabled,
		CreatedAt:   source.CreatedAt,
		UpdatedAt:   source.UpdatedAt,
	}

	if source.NotionDBConfig != nil {
		gqlSource.Config = &graphql1.NotionDBConfig{
			DatabaseID:    source.NotionDBConfig.DatabaseID,
			DatabaseTitle: source.NotionDBConfig.DatabaseTitle,
			DatabaseURL:   source.NotionDBConfig.DatabaseURL,
		}
	}

	if source.NotionPageConfig != nil {
		gqlSource.Config = &graphql1.NotionPageConfig{
			PageID:    source.NotionPageConfig.PageID,
			PageTitle: source.NotionPageConfig.PageTitle,
			PageURL:   source.NotionPageConfig.PageURL,
			Recursive: source.NotionPageConfig.Recursive,
			MaxDepth:  source.NotionPageConfig.MaxDepth,
		}
	}

	if source.SlackConfig != nil {
		channels := make([]*graphql1.SlackChannel, len(source.SlackConfig.Channels))
		for i, ch := range source.SlackConfig.Channels {
			channels[i] = &graphql1.SlackChannel{
				ID:   ch.ID,
				Name: ch.Name,
			}
		}
		gqlSource.Config = &graphql1.SlackConfig{
			Channels: channels,
		}
	}

	if source.GitHubConfig != nil {
		repos := make([]*graphql1.GitHubRepository, len(source.GitHubConfig.Repositories))
		for i, r := range source.GitHubConfig.Repositories {
			repos[i] = &graphql1.GitHubRepository{
				Owner: r.Owner,
				Repo:  r.Repo,
			}
		}
		gqlSource.Config = &graphql1.GitHubConfig{
			Repositories: repos,
		}
	}

	return gqlSource, nil
}

// toGraphQLSourceType converts domain SourceType to GraphQL SourceType
func toGraphQLSourceType(st model.SourceType) (graphql1.SourceType, error) {
	switch st {
	case model.SourceTypeNotionDB:
		return graphql1.SourceTypeNotionDb, nil
	case model.SourceTypeNotionPage:
		return graphql1.SourceTypeNotionPage, nil
	case model.SourceTypeSlack:
		// NOTE: SourceTypeSLACk (not SourceTypeSLACK) is generated by gqlgen.
		// gqlgen treats consecutive uppercase letters as an acronym and applies
		// its naming convention, resulting in "SLACk" instead of "SLACK".
		return graphql1.SourceTypeSLACk, nil
	case model.SourceTypeGitHub:
		return graphql1.SourceTypeGithub, nil
	default:
		return "", goerr.New("unsupported source type", goerr.V("sourceType", st))
	}
}

// toUseCaseCreateNotionDBSourceInput converts GraphQL input to UseCase input
func toUseCaseCreateNotionDBSourceInput(input graphql1.CreateNotionDBSourceInput) usecase.CreateNotionDBSourceInput {
	ucInput := usecase.CreateNotionDBSourceInput{
		DatabaseID: input.DatabaseID,
	}
	if input.Name != nil {
		ucInput.Name = *input.Name
	}
	if input.Description != nil {
		ucInput.Description = *input.Description
	}
	if input.Enabled != nil {
		ucInput.Enabled = *input.Enabled
	} else {
		ucInput.Enabled = true
	}
	return ucInput
}

// toUseCaseCreateNotionPageSourceInput converts GraphQL input to UseCase input
func toUseCaseCreateNotionPageSourceInput(input graphql1.CreateNotionPageSourceInput) usecase.CreateNotionPageSourceInput {
	ucInput := usecase.CreateNotionPageSourceInput{
		PageID: input.PageID,
	}
	if input.Name != nil {
		ucInput.Name = *input.Name
	}
	if input.Description != nil {
		ucInput.Description = *input.Description
	}
	if input.Enabled != nil {
		ucInput.Enabled = *input.Enabled
	} else {
		ucInput.Enabled = true
	}
	if input.Recursive != nil {
		ucInput.Recursive = *input.Recursive
	}
	if input.MaxDepth != nil {
		ucInput.MaxDepth = *input.MaxDepth
	}
	return ucInput
}

// toUseCaseUpdateSourceInput converts GraphQL input to UseCase input
func toUseCaseUpdateSourceInput(input graphql1.UpdateSourceInput) usecase.UpdateSourceInput {
	return usecase.UpdateSourceInput{
		ID:          model.SourceID(input.ID),
		Name:        input.Name,
		Description: input.Description,
		Enabled:     input.Enabled,
	}
}

// toUseCaseCreateSlackSourceInput converts GraphQL input to UseCase input
func toUseCaseCreateSlackSourceInput(input graphql1.CreateSlackSourceInput) usecase.CreateSlackSourceInput {
	ucInput := usecase.CreateSlackSourceInput{
		ChannelIDs: input.ChannelIDs,
	}
	if input.Name != nil {
		ucInput.Name = *input.Name
	}
	if input.Description != nil {
		ucInput.Description = *input.Description
	}
	if input.Enabled != nil {
		ucInput.Enabled = *input.Enabled
	} else {
		ucInput.Enabled = true
	}
	return ucInput
}

// toUseCaseUpdateSlackSourceInput converts GraphQL input to UseCase input
func toUseCaseUpdateSlackSourceInput(input graphql1.UpdateSlackSourceInput) usecase.UpdateSlackSourceInput {
	return usecase.UpdateSlackSourceInput{
		ID:          model.SourceID(input.ID),
		Name:        input.Name,
		Description: input.Description,
		ChannelIDs:  input.ChannelIDs,
		Enabled:     input.Enabled,
	}
}

// toUseCaseCreateGitHubSourceInput converts GraphQL input to UseCase input
func toUseCaseCreateGitHubSourceInput(input graphql1.CreateGitHubSourceInput) usecase.CreateGitHubSourceInput {
	ucInput := usecase.CreateGitHubSourceInput{
		Repositories: input.Repositories,
	}
	if input.Name != nil {
		ucInput.Name = *input.Name
	}
	if input.Description != nil {
		ucInput.Description = *input.Description
	}
	if input.Enabled != nil {
		ucInput.Enabled = *input.Enabled
	} else {
		ucInput.Enabled = true
	}
	return ucInput
}

// toUseCaseUpdateGitHubSourceInput converts GraphQL input to UseCase input
func toUseCaseUpdateGitHubSourceInput(input graphql1.UpdateGitHubSourceInput) usecase.UpdateGitHubSourceInput {
	return usecase.UpdateGitHubSourceInput{
		ID:           model.SourceID(input.ID),
		Name:         input.Name,
		Description:  input.Description,
		Repositories: input.Repositories,
		Enabled:      input.Enabled,
	}
}
