# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: graphql
      - task: mock

  graphql:
    desc: "Generate GraphQL code"
    cmds:
      - go tool gqlgen generate

  mock:
    aliases:
      - m
    desc: "Generate mock files"
    cmds:
      - echo "Mock generation will be added when interfaces are defined"

  test:e2e:
    desc: "Run E2E tests with Playwright (includes backend startup and teardown)"
    cmds:
      - ./frontend/scripts/e2e.sh
