# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: graphql
      - task: mock

  graphql:
    desc: "Generate GraphQL code"
    cmds:
      - go tool gqlgen generate

  mock:
    aliases:
      - m
    desc: "Generate mock files"
    cmds:
      - echo "Mock generation will be added when interfaces are defined"

  test:e2e:
    desc: "Run E2E tests with Playwright"
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run test:e2e

  test:e2e:ui:
    desc: "Run E2E tests with Playwright UI"
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run test:e2e:ui

  test:e2e:headed:
    desc: "Run E2E tests in headed mode"
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run test:e2e:headed

  test:e2e:debug:
    desc: "Run E2E tests in debug mode"
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run test:e2e:debug

  test:e2e:report:
    desc: "Show E2E test report"
    dir: frontend
    cmds:
      - pnpm run test:e2e:report
