// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/secmon-lab/hecatoncheires/pkg/domain/types"
)

type SourceConfig interface {
	IsSourceConfig()
}

type ActionConfig struct {
	Initial  string                    `json:"initial"`
	Closed   []string                  `json:"closed"`
	Statuses []*ActionStatusDefinition `json:"statuses"`
}

type ActionEvent struct {
	ID        string          `json:"id"`
	ActionID  int             `json:"actionID"`
	Kind      ActionEventKind `json:"kind"`
	ActorID   string          `json:"actorID"`
	Actor     *SlackUser      `json:"actor,omitempty"`
	OldValue  string          `json:"oldValue"`
	NewValue  string          `json:"newValue"`
	CreatedAt time.Time       `json:"createdAt"`
}

type ActionEventConnection struct {
	Items      []*ActionEvent `json:"items"`
	NextCursor string         `json:"nextCursor"`
}

type ActionStatusDefinition struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
	Emoji       *string `json:"emoji,omitempty"`
}

type ActionStep struct {
	ID            string     `json:"id"`
	ActionID      int        `json:"actionID"`
	Title         string     `json:"title"`
	Done          bool       `json:"done"`
	DoneAt        *time.Time `json:"doneAt,omitempty"`
	DoneBy        *string    `json:"doneBy,omitempty"`
	DoneByUser    *SlackUser `json:"doneByUser,omitempty"`
	CreatedBy     string     `json:"createdBy"`
	CreatedByUser *SlackUser `json:"createdByUser,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
}

type ActionStepProgress struct {
	Done  int `json:"done"`
	Total int `json:"total"`
}

type AddActionStepInput struct {
	ActionID int    `json:"actionId"`
	Title    string `json:"title"`
}

type AssistLog struct {
	ID        string    `json:"id"`
	CaseID    int       `json:"caseId"`
	Summary   string    `json:"summary"`
	Actions   string    `json:"actions"`
	Reasoning string    `json:"reasoning"`
	NextSteps string    `json:"nextSteps"`
	CreatedAt time.Time `json:"createdAt"`
}

type AssistLogConnection struct {
	Items      []*AssistLog `json:"items"`
	TotalCount int          `json:"totalCount"`
	HasMore    bool         `json:"hasMore"`
}

// A referenceable case (non-private, non-draft) used by case_ref fields.
type CaseRef struct {
	ID          int              `json:"id"`
	Title       string           `json:"title"`
	Status      types.CaseStatus `json:"status"`
	WorkspaceID string           `json:"workspaceId"`
}

type ChannelUserConnection struct {
	Items      []*SlackUser `json:"items"`
	TotalCount int          `json:"totalCount"`
	HasMore    bool         `json:"hasMore"`
}

type CreateActionInput struct {
	CaseID         int        `json:"caseID"`
	Title          string     `json:"title"`
	Description    *string    `json:"description,omitempty"`
	AssigneeID     *string    `json:"assigneeID,omitempty"`
	SlackMessageTs *string    `json:"slackMessageTS,omitempty"`
	Status         *string    `json:"status,omitempty"`
	DueDate        *time.Time `json:"dueDate,omitempty"`
}

type CreateCaseImportInput struct {
	// Raw YAML content (UTF-8).
	Content string `json:"content"`
	// Optional original file name for display purposes.
	OriginalFileName *string `json:"originalFileName,omitempty"`
}

type CreateCaseInput struct {
	Title       string             `json:"title"`
	Description *string            `json:"description,omitempty"`
	AssigneeIDs []string           `json:"assigneeIDs,omitempty"`
	Fields      []*FieldValueInput `json:"fields,omitempty"`
	IsPrivate   *bool              `json:"isPrivate,omitempty"`
}

type CreateDraftInput struct {
	Title       *string            `json:"title,omitempty"`
	Description *string            `json:"description,omitempty"`
	AssigneeIDs []string           `json:"assigneeIDs,omitempty"`
	Fields      []*FieldValueInput `json:"fields,omitempty"`
	IsPrivate   *bool              `json:"isPrivate,omitempty"`
}

type CreateGitHubSourceInput struct {
	Name         *string  `json:"name,omitempty"`
	Description  *string  `json:"description,omitempty"`
	Repositories []string `json:"repositories"`
	Enabled      *bool    `json:"enabled,omitempty"`
}

type CreateKnowledgeInput struct {
	Title string   `json:"title"`
	Claim *string  `json:"claim,omitempty"`
	Tags  []string `json:"tags"`
}

type CreateMemoInput struct {
	CaseID int                `json:"caseID"`
	Title  string             `json:"title"`
	Fields []*FieldValueInput `json:"fields,omitempty"`
}

type CreateNotionDBSourceInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	DatabaseID  string  `json:"databaseID"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type CreateNotionPageSourceInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	PageID      string  `json:"pageID"`
	Enabled     *bool   `json:"enabled,omitempty"`
	Recursive   *bool   `json:"recursive,omitempty"`
	MaxDepth    *int    `json:"maxDepth,omitempty"`
}

type CreateSlackSourceInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	ChannelIDs  []string `json:"channelIDs"`
	Enabled     *bool    `json:"enabled,omitempty"`
}

type DeleteActionStepInput struct {
	ActionID int    `json:"actionId"`
	StepID   string `json:"stepId"`
}

type EntityLabels struct {
	Case string `json:"case"`
}

type FieldConfiguration struct {
	Fields       []*FieldDefinition `json:"fields"`
	Labels       *EntityLabels      `json:"labels"`
	ActionConfig *ActionConfig      `json:"actionConfig"`
}

type FieldDefinition struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Type                 FieldType      `json:"type"`
	Required             bool           `json:"required"`
	Description          *string        `json:"description,omitempty"`
	Options              []*FieldOption `json:"options,omitempty"`
	ReferenceWorkspaceID *string        `json:"referenceWorkspaceId,omitempty"`
}

type FieldOption struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Metadata    *string `json:"metadata,omitempty"`
}

type FieldValue struct {
	FieldID string `json:"fieldId"`
	Value   any    `json:"value"`
}

type FieldValueInput struct {
	FieldID string `json:"fieldId"`
	Value   any    `json:"value"`
}

type GitHubConfig struct {
	Repositories []*GitHubRepository `json:"repositories"`
}

func (GitHubConfig) IsSourceConfig() {}

type GitHubRepoValidationResult struct {
	Valid                bool    `json:"valid"`
	Owner                *string `json:"owner,omitempty"`
	Repo                 *string `json:"repo,omitempty"`
	FullName             *string `json:"fullName,omitempty"`
	Description          *string `json:"description,omitempty"`
	IsPrivate            *bool   `json:"isPrivate,omitempty"`
	PullRequestCount     *int    `json:"pullRequestCount,omitempty"`
	IssueCount           *int    `json:"issueCount,omitempty"`
	CanFetchPullRequests bool    `json:"canFetchPullRequests"`
	CanFetchIssues       bool    `json:"canFetchIssues"`
	ErrorMessage         *string `json:"errorMessage,omitempty"`
}

type GitHubRepository struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

type ImportActionResult struct {
	Status          ImportItemResultStatus `json:"status"`
	CreatedAction   *Action                `json:"createdAction,omitempty"`
	CreatedActionID *int                   `json:"createdActionID,omitempty"`
	Error           *ImportIssue           `json:"error,omitempty"`
}

type ImportCaseResult struct {
	Status        ImportItemResultStatus `json:"status"`
	CreatedCase   *Case                  `json:"createdCase,omitempty"`
	CreatedCaseID *int                   `json:"createdCaseID,omitempty"`
	Error         *ImportIssue           `json:"error,omitempty"`
}

type ImportIssue struct {
	Path     string              `json:"path"`
	Message  string              `json:"message"`
	Severity ImportIssueSeverity `json:"severity"`
}

type ImportSession struct {
	ID              string              `json:"id"`
	WorkspaceID     string              `json:"workspaceID"`
	CreatorUserID   string              `json:"creatorUserID"`
	Status          ImportSessionStatus `json:"status"`
	Source          *ImportSource       `json:"source"`
	Snapshot        *ImportSnapshot     `json:"snapshot"`
	Issues          []*ImportIssue      `json:"issues"`
	Valid           bool                `json:"valid"`
	FieldSchemaHash string              `json:"fieldSchemaHash"`
	CreatedAt       time.Time           `json:"createdAt"`
	UpdatedAt       time.Time           `json:"updatedAt"`
	ExecutedAt      *time.Time          `json:"executedAt,omitempty"`
	CreatedCount    int                 `json:"createdCount"`
	FailedCount     int                 `json:"failedCount"`
	SkippedCount    int                 `json:"skippedCount"`
}

type ImportSnapshot struct {
	Version int                   `json:"version"`
	Cases   []*ImportSnapshotCase `json:"cases"`
}

type ImportSnapshotAction struct {
	Index       int                 `json:"index"`
	Title       string              `json:"title"`
	Description *string             `json:"description,omitempty"`
	AssigneeID  *string             `json:"assigneeID,omitempty"`
	DueDate     *time.Time          `json:"dueDate,omitempty"`
	Issues      []*ImportIssue      `json:"issues"`
	Result      *ImportActionResult `json:"result"`
}

type ImportSnapshotCase struct {
	Index       int      `json:"index"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	IsPrivate   bool     `json:"isPrivate"`
	AssigneeIDs []string `json:"assigneeIDs"`
	// Slack users referenced by assigneeIDs, resolved on the server. Lookup is
	//   batched per request so the frontend never has to ship the full slackUsers
	//   list. IDs that cannot be resolved are simply omitted from the array.
	Assignees []*SlackUser            `json:"assignees"`
	Fields    []*ImportSnapshotField  `json:"fields"`
	Actions   []*ImportSnapshotAction `json:"actions"`
	Issues    []*ImportIssue          `json:"issues"`
	Result    *ImportCaseResult       `json:"result"`
}

type ImportSnapshotField struct {
	Key     string `json:"key"`
	Display string `json:"display"`
}

type ImportSource struct {
	OriginalFileName string `json:"originalFileName"`
	SizeBytes        int    `json:"sizeBytes"`
}

type JobRunEvent struct {
	EventID        string          `json:"eventId"`
	RunID          string          `json:"runId"`
	Sequence       int             `json:"sequence"`
	OccurredAt     time.Time       `json:"occurredAt"`
	Kind           JobRunEventKind `json:"kind"`
	ParentSequence int             `json:"parentSequence"`
	Phase          string          `json:"phase"`
	AgentLabel     string          `json:"agentLabel"`
	Payload        string          `json:"payload"`
}

type JobRunLog struct {
	WorkspaceID    string      `json:"workspaceId"`
	CaseID         int         `json:"caseId"`
	JobID          string      `json:"jobId"`
	JobName        string      `json:"jobName"`
	Strategy       JobStrategy `json:"strategy"`
	RunID          string      `json:"runId"`
	TraceID        string      `json:"traceId"`
	Stage          JobRunStage `json:"stage"`
	StartedAt      time.Time   `json:"startedAt"`
	EndedAt        *time.Time  `json:"endedAt,omitempty"`
	DurationMs     *int        `json:"durationMs,omitempty"`
	ErrorMessage   string      `json:"errorMessage"`
	SystemPrompt   string      `json:"systemPrompt"`
	EventType      string      `json:"eventType"`
	EventTriggerAt time.Time   `json:"eventTriggerAt"`
}

type JobRunLogConnection struct {
	Items      []*JobRunLog `json:"items"`
	NextCursor *string      `json:"nextCursor,omitempty"`
}

type Knowledge struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Claim     string    `json:"claim"`
	Tags      []string  `json:"tags"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MemoConfiguration struct {
	Description string             `json:"description"`
	Fields      []*FieldDefinition `json:"fields"`
}

type Mutation struct {
}

type NotionDBConfig struct {
	DatabaseID    string `json:"databaseID"`
	DatabaseTitle string `json:"databaseTitle"`
	DatabaseURL   string `json:"databaseURL"`
}

func (NotionDBConfig) IsSourceConfig() {}

type NotionDBValidationResult struct {
	Valid         bool    `json:"valid"`
	DatabaseTitle *string `json:"databaseTitle,omitempty"`
	DatabaseURL   *string `json:"databaseURL,omitempty"`
	ErrorMessage  *string `json:"errorMessage,omitempty"`
}

type NotionPageConfig struct {
	PageID    string `json:"pageID"`
	PageTitle string `json:"pageTitle"`
	PageURL   string `json:"pageURL"`
	Recursive bool   `json:"recursive"`
	MaxDepth  int    `json:"maxDepth"`
}

func (NotionPageConfig) IsSourceConfig() {}

type NotionPageValidationResult struct {
	Valid        bool    `json:"valid"`
	PageTitle    *string `json:"pageTitle,omitempty"`
	PageURL      *string `json:"pageURL,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

type Query struct {
}

type RenameActionStepInput struct {
	ActionID int    `json:"actionId"`
	StepID   string `json:"stepId"`
	Title    string `json:"title"`
}

type SetActionStepDoneInput struct {
	ActionID int    `json:"actionId"`
	StepID   string `json:"stepId"`
	Done     bool   `json:"done"`
}

type SlackChannel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SlackChannelInfo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SlackConfig struct {
	Channels []*SlackChannel `json:"channels"`
}

func (SlackConfig) IsSourceConfig() {}

type SlackFile struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Mimetype   string  `json:"mimetype"`
	Filetype   string  `json:"filetype"`
	Size       int     `json:"size"`
	URLPrivate string  `json:"urlPrivate"`
	Permalink  string  `json:"permalink"`
	ThumbURL   *string `json:"thumbURL,omitempty"`
}

type SlackMessage struct {
	ID        string       `json:"id"`
	ChannelID string       `json:"channelID"`
	ThreadTs  *string      `json:"threadTS,omitempty"`
	TeamID    string       `json:"teamID"`
	UserID    string       `json:"userID"`
	UserName  string       `json:"userName"`
	Text      string       `json:"text"`
	Files     []*SlackFile `json:"files"`
	CreatedAt time.Time    `json:"createdAt"`
}

type SlackMessageConnection struct {
	Items      []*SlackMessage `json:"items"`
	NextCursor string          `json:"nextCursor"`
}

type SlackUser struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	RealName string  `json:"realName"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type Source struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	SourceType  SourceType   `json:"sourceType"`
	Description string       `json:"description"`
	Enabled     bool         `json:"enabled"`
	Config      SourceConfig `json:"config"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

type SubmitDraftInput struct {
	Title       *string            `json:"title,omitempty"`
	Description *string            `json:"description,omitempty"`
	Fields      []*FieldValueInput `json:"fields,omitempty"`
}

type UpdateActionInput struct {
	ID             int        `json:"id"`
	CaseID         *int       `json:"caseID,omitempty"`
	Title          *string    `json:"title,omitempty"`
	Description    *string    `json:"description,omitempty"`
	AssigneeID     *string    `json:"assigneeID,omitempty"`
	SlackMessageTs *string    `json:"slackMessageTS,omitempty"`
	Status         *string    `json:"status,omitempty"`
	DueDate        *time.Time `json:"dueDate,omitempty"`
	ClearDueDate   *bool      `json:"clearDueDate,omitempty"`
	ClearAssignee  *bool      `json:"clearAssignee,omitempty"`
}

type UpdateCaseAgentSettingsInput struct {
	CaseID                int      `json:"caseId"`
	AgentAdditionalPrompt string   `json:"agentAdditionalPrompt"`
	EnabledSourceIds      []string `json:"enabledSourceIds"`
}

type UpdateCaseInput struct {
	ID          int                `json:"id"`
	Title       *string            `json:"title,omitempty"`
	Description *string            `json:"description,omitempty"`
	Fields      []*FieldValueInput `json:"fields,omitempty"`
}

type UpdateCaseStatusInput struct {
	ID     int    `json:"id"`
	Status string `json:"status"`
}

type UpdateGitHubSourceInput struct {
	ID           string   `json:"id"`
	Name         *string  `json:"name,omitempty"`
	Description  *string  `json:"description,omitempty"`
	Repositories []string `json:"repositories,omitempty"`
	Enabled      *bool    `json:"enabled,omitempty"`
}

type UpdateKnowledgeInput struct {
	ID    string   `json:"id"`
	Title *string  `json:"title,omitempty"`
	Claim *string  `json:"claim,omitempty"`
	Tags  []string `json:"tags,omitempty"`
}

type UpdateMemoInput struct {
	ID     string             `json:"id"`
	CaseID int                `json:"caseID"`
	Title  *string            `json:"title,omitempty"`
	Fields []*FieldValueInput `json:"fields,omitempty"`
}

type UpdateNotionDBSourceInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	DatabaseID  *string `json:"databaseID,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type UpdateNotionPageSourceInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	PageID      *string `json:"pageID,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
	Recursive   *bool   `json:"recursive,omitempty"`
	MaxDepth    *int    `json:"maxDepth,omitempty"`
}

type UpdateSlackSourceInput struct {
	ID          string   `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	ChannelIDs  []string `json:"channelIDs,omitempty"`
	Enabled     *bool    `json:"enabled,omitempty"`
}

type UpdateSourceInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type Workspace struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ActionArchiveFilter string

const (
	ActionArchiveFilterActive   ActionArchiveFilter = "ACTIVE"
	ActionArchiveFilterArchived ActionArchiveFilter = "ARCHIVED"
	ActionArchiveFilterAll      ActionArchiveFilter = "ALL"
)

var AllActionArchiveFilter = []ActionArchiveFilter{
	ActionArchiveFilterActive,
	ActionArchiveFilterArchived,
	ActionArchiveFilterAll,
}

func (e ActionArchiveFilter) IsValid() bool {
	switch e {
	case ActionArchiveFilterActive, ActionArchiveFilterArchived, ActionArchiveFilterAll:
		return true
	}
	return false
}

func (e ActionArchiveFilter) String() string {
	return string(e)
}

func (e *ActionArchiveFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionArchiveFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionArchiveFilter", str)
	}
	return nil
}

func (e ActionArchiveFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActionArchiveFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActionArchiveFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ActionEventKind string

const (
	ActionEventKindCreated          ActionEventKind = "CREATED"
	ActionEventKindTitleChanged     ActionEventKind = "TITLE_CHANGED"
	ActionEventKindStatusChanged    ActionEventKind = "STATUS_CHANGED"
	ActionEventKindAssigneeChanged  ActionEventKind = "ASSIGNEE_CHANGED"
	ActionEventKindArchived         ActionEventKind = "ARCHIVED"
	ActionEventKindUnarchived       ActionEventKind = "UNARCHIVED"
	ActionEventKindStepAdded        ActionEventKind = "STEP_ADDED"
	ActionEventKindStepRemoved      ActionEventKind = "STEP_REMOVED"
	ActionEventKindStepDone         ActionEventKind = "STEP_DONE"
	ActionEventKindStepReopened     ActionEventKind = "STEP_REOPENED"
	ActionEventKindStepTitleChanged ActionEventKind = "STEP_TITLE_CHANGED"
)

var AllActionEventKind = []ActionEventKind{
	ActionEventKindCreated,
	ActionEventKindTitleChanged,
	ActionEventKindStatusChanged,
	ActionEventKindAssigneeChanged,
	ActionEventKindArchived,
	ActionEventKindUnarchived,
	ActionEventKindStepAdded,
	ActionEventKindStepRemoved,
	ActionEventKindStepDone,
	ActionEventKindStepReopened,
	ActionEventKindStepTitleChanged,
}

func (e ActionEventKind) IsValid() bool {
	switch e {
	case ActionEventKindCreated, ActionEventKindTitleChanged, ActionEventKindStatusChanged, ActionEventKindAssigneeChanged, ActionEventKindArchived, ActionEventKindUnarchived, ActionEventKindStepAdded, ActionEventKindStepRemoved, ActionEventKindStepDone, ActionEventKindStepReopened, ActionEventKindStepTitleChanged:
		return true
	}
	return false
}

func (e ActionEventKind) String() string {
	return string(e)
}

func (e *ActionEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionEventKind", str)
	}
	return nil
}

func (e ActionEventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActionEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActionEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FieldType string

const (
	FieldTypeText         FieldType = "TEXT"
	FieldTypeNumber       FieldType = "NUMBER"
	FieldTypeSelect       FieldType = "SELECT"
	FieldTypeMultiSelect  FieldType = "MULTI_SELECT"
	FieldTypeUser         FieldType = "USER"
	FieldTypeMultiUser    FieldType = "MULTI_USER"
	FieldTypeDate         FieldType = "DATE"
	FieldTypeURL          FieldType = "URL"
	FieldTypeCaseRef      FieldType = "CASE_REF"
	FieldTypeMultiCaseRef FieldType = "MULTI_CASE_REF"
)

var AllFieldType = []FieldType{
	FieldTypeText,
	FieldTypeNumber,
	FieldTypeSelect,
	FieldTypeMultiSelect,
	FieldTypeUser,
	FieldTypeMultiUser,
	FieldTypeDate,
	FieldTypeURL,
	FieldTypeCaseRef,
	FieldTypeMultiCaseRef,
}

func (e FieldType) IsValid() bool {
	switch e {
	case FieldTypeText, FieldTypeNumber, FieldTypeSelect, FieldTypeMultiSelect, FieldTypeUser, FieldTypeMultiUser, FieldTypeDate, FieldTypeURL, FieldTypeCaseRef, FieldTypeMultiCaseRef:
		return true
	}
	return false
}

func (e FieldType) String() string {
	return string(e)
}

func (e *FieldType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldType", str)
	}
	return nil
}

func (e FieldType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportIssueSeverity string

const (
	ImportIssueSeverityError   ImportIssueSeverity = "ERROR"
	ImportIssueSeverityWarning ImportIssueSeverity = "WARNING"
)

var AllImportIssueSeverity = []ImportIssueSeverity{
	ImportIssueSeverityError,
	ImportIssueSeverityWarning,
}

func (e ImportIssueSeverity) IsValid() bool {
	switch e {
	case ImportIssueSeverityError, ImportIssueSeverityWarning:
		return true
	}
	return false
}

func (e ImportIssueSeverity) String() string {
	return string(e)
}

func (e *ImportIssueSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportIssueSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportIssueSeverity", str)
	}
	return nil
}

func (e ImportIssueSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportIssueSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportIssueSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportItemResultStatus string

const (
	ImportItemResultStatusPending ImportItemResultStatus = "PENDING"
	ImportItemResultStatusCreated ImportItemResultStatus = "CREATED"
	ImportItemResultStatusFailed  ImportItemResultStatus = "FAILED"
	ImportItemResultStatusSkipped ImportItemResultStatus = "SKIPPED"
)

var AllImportItemResultStatus = []ImportItemResultStatus{
	ImportItemResultStatusPending,
	ImportItemResultStatusCreated,
	ImportItemResultStatusFailed,
	ImportItemResultStatusSkipped,
}

func (e ImportItemResultStatus) IsValid() bool {
	switch e {
	case ImportItemResultStatusPending, ImportItemResultStatusCreated, ImportItemResultStatusFailed, ImportItemResultStatusSkipped:
		return true
	}
	return false
}

func (e ImportItemResultStatus) String() string {
	return string(e)
}

func (e *ImportItemResultStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportItemResultStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportItemResultStatus", str)
	}
	return nil
}

func (e ImportItemResultStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportItemResultStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportItemResultStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportSessionStatus string

const (
	ImportSessionStatusPending ImportSessionStatus = "PENDING"
	ImportSessionStatusApplied ImportSessionStatus = "APPLIED"
	ImportSessionStatusFailed  ImportSessionStatus = "FAILED"
)

var AllImportSessionStatus = []ImportSessionStatus{
	ImportSessionStatusPending,
	ImportSessionStatusApplied,
	ImportSessionStatusFailed,
}

func (e ImportSessionStatus) IsValid() bool {
	switch e {
	case ImportSessionStatusPending, ImportSessionStatusApplied, ImportSessionStatusFailed:
		return true
	}
	return false
}

func (e ImportSessionStatus) String() string {
	return string(e)
}

func (e *ImportSessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportSessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportSessionStatus", str)
	}
	return nil
}

func (e ImportSessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportSessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportSessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobRunEventKind string

const (
	JobRunEventKindLlmRequest  JobRunEventKind = "LLM_REQUEST"
	JobRunEventKindLlmResponse JobRunEventKind = "LLM_RESPONSE"
	JobRunEventKindToolCall    JobRunEventKind = "TOOL_CALL"
	JobRunEventKindRunError    JobRunEventKind = "RUN_ERROR"
)

var AllJobRunEventKind = []JobRunEventKind{
	JobRunEventKindLlmRequest,
	JobRunEventKindLlmResponse,
	JobRunEventKindToolCall,
	JobRunEventKindRunError,
}

func (e JobRunEventKind) IsValid() bool {
	switch e {
	case JobRunEventKindLlmRequest, JobRunEventKindLlmResponse, JobRunEventKindToolCall, JobRunEventKindRunError:
		return true
	}
	return false
}

func (e JobRunEventKind) String() string {
	return string(e)
}

func (e *JobRunEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobRunEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobRunEventKind", str)
	}
	return nil
}

func (e JobRunEventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobRunEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobRunEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobRunStage string

const (
	JobRunStageRunning JobRunStage = "RUNNING"
	JobRunStageSuccess JobRunStage = "SUCCESS"
	JobRunStageFailed  JobRunStage = "FAILED"
)

var AllJobRunStage = []JobRunStage{
	JobRunStageRunning,
	JobRunStageSuccess,
	JobRunStageFailed,
}

func (e JobRunStage) IsValid() bool {
	switch e {
	case JobRunStageRunning, JobRunStageSuccess, JobRunStageFailed:
		return true
	}
	return false
}

func (e JobRunStage) String() string {
	return string(e)
}

func (e *JobRunStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobRunStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobRunStage", str)
	}
	return nil
}

func (e JobRunStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobRunStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobRunStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStrategy string

const (
	JobStrategySimple   JobStrategy = "SIMPLE"
	JobStrategyPlanexec JobStrategy = "PLANEXEC"
)

var AllJobStrategy = []JobStrategy{
	JobStrategySimple,
	JobStrategyPlanexec,
}

func (e JobStrategy) IsValid() bool {
	switch e {
	case JobStrategySimple, JobStrategyPlanexec:
		return true
	}
	return false
}

func (e JobStrategy) String() string {
	return string(e)
}

func (e *JobStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStrategy", str)
	}
	return nil
}

func (e JobStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemoArchiveFilter string

const (
	MemoArchiveFilterActive   MemoArchiveFilter = "ACTIVE"
	MemoArchiveFilterArchived MemoArchiveFilter = "ARCHIVED"
	MemoArchiveFilterAll      MemoArchiveFilter = "ALL"
)

var AllMemoArchiveFilter = []MemoArchiveFilter{
	MemoArchiveFilterActive,
	MemoArchiveFilterArchived,
	MemoArchiveFilterAll,
}

func (e MemoArchiveFilter) IsValid() bool {
	switch e {
	case MemoArchiveFilterActive, MemoArchiveFilterArchived, MemoArchiveFilterAll:
		return true
	}
	return false
}

func (e MemoArchiveFilter) String() string {
	return string(e)
}

func (e *MemoArchiveFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemoArchiveFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemoArchiveFilter", str)
	}
	return nil
}

func (e MemoArchiveFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemoArchiveFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemoArchiveFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourceType string

const (
	SourceTypeNotionDb   SourceType = "NOTION_DB"
	SourceTypeNotionPage SourceType = "NOTION_PAGE"
	SourceTypeSLACk      SourceType = "SLACK"
	SourceTypeGithub     SourceType = "GITHUB"
)

var AllSourceType = []SourceType{
	SourceTypeNotionDb,
	SourceTypeNotionPage,
	SourceTypeSLACk,
	SourceTypeGithub,
}

func (e SourceType) IsValid() bool {
	switch e {
	case SourceTypeNotionDb, SourceTypeNotionPage, SourceTypeSLACk, SourceTypeGithub:
		return true
	}
	return false
}

func (e SourceType) String() string {
	return string(e)
}

func (e *SourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceType", str)
	}
	return nil
}

func (e SourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
