// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type SourceConfig interface {
	IsSourceConfig()
}

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateNotionDBSourceInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	DatabaseID  string  `json:"databaseID"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type CreateResponseInput struct {
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	ResponderIDs []string        `json:"responderIDs"`
	URL          *string         `json:"url,omitempty"`
	Status       *ResponseStatus `json:"status,omitempty"`
	RiskIDs      []int           `json:"riskIDs,omitempty"`
}

type CreateRiskInput struct {
	Name                string   `json:"name"`
	Description         string   `json:"description"`
	CategoryIDs         []string `json:"categoryIDs"`
	SpecificImpact      string   `json:"specificImpact"`
	LikelihoodID        string   `json:"likelihoodID"`
	ImpactID            string   `json:"impactID"`
	ResponseTeamIDs     []string `json:"responseTeamIDs"`
	AssigneeIDs         []string `json:"assigneeIDs"`
	DetectionIndicators string   `json:"detectionIndicators"`
}

type CreateSlackSourceInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	ChannelIDs  []string `json:"channelIDs"`
	Enabled     *bool    `json:"enabled,omitempty"`
}

type ImpactLevel struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Score       int    `json:"score"`
}

type LikelihoodLevel struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Score       int    `json:"score"`
}

type Mutation struct {
}

type NotionDBConfig struct {
	DatabaseID    string `json:"databaseID"`
	DatabaseTitle string `json:"databaseTitle"`
	DatabaseURL   string `json:"databaseURL"`
}

func (NotionDBConfig) IsSourceConfig() {}

type NotionDBValidationResult struct {
	Valid         bool    `json:"valid"`
	DatabaseTitle *string `json:"databaseTitle,omitempty"`
	DatabaseURL   *string `json:"databaseURL,omitempty"`
	ErrorMessage  *string `json:"errorMessage,omitempty"`
}

type Query struct {
}

type Response struct {
	ID          int            `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Responders  []*SlackUser   `json:"responders"`
	URL         *string        `json:"url,omitempty"`
	Status      ResponseStatus `json:"status"`
	Risks       []*Risk        `json:"risks"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Risk struct {
	ID                  int              `json:"id"`
	Name                string           `json:"name"`
	Description         string           `json:"description"`
	CategoryIDs         []string         `json:"categoryIDs"`
	Categories          []*Category      `json:"categories"`
	SpecificImpact      string           `json:"specificImpact"`
	LikelihoodID        string           `json:"likelihoodID"`
	LikelihoodLevel     *LikelihoodLevel `json:"likelihoodLevel,omitempty"`
	ImpactID            string           `json:"impactID"`
	ImpactLevel         *ImpactLevel     `json:"impactLevel,omitempty"`
	ResponseTeamIDs     []string         `json:"responseTeamIDs"`
	ResponseTeams       []*Team          `json:"responseTeams"`
	AssigneeIDs         []string         `json:"assigneeIDs"`
	Assignees           []*SlackUser     `json:"assignees"`
	DetectionIndicators string           `json:"detectionIndicators"`
	Responses           []*Response      `json:"responses"`
	CreatedAt           time.Time        `json:"createdAt"`
	UpdatedAt           time.Time        `json:"updatedAt"`
}

type RiskConfiguration struct {
	Categories       []*Category        `json:"categories"`
	LikelihoodLevels []*LikelihoodLevel `json:"likelihoodLevels"`
	ImpactLevels     []*ImpactLevel     `json:"impactLevels"`
	Teams            []*Team            `json:"teams"`
}

type SlackChannel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SlackChannelInfo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SlackConfig struct {
	Channels []*SlackChannel `json:"channels"`
}

func (SlackConfig) IsSourceConfig() {}

type SlackUser struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	RealName string  `json:"realName"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type Source struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	SourceType  SourceType   `json:"sourceType"`
	Description string       `json:"description"`
	Enabled     bool         `json:"enabled"`
	Config      SourceConfig `json:"config"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

type Team struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateResponseInput struct {
	ID           int             `json:"id"`
	Title        *string         `json:"title,omitempty"`
	Description  *string         `json:"description,omitempty"`
	ResponderIDs []string        `json:"responderIDs,omitempty"`
	URL          *string         `json:"url,omitempty"`
	Status       *ResponseStatus `json:"status,omitempty"`
	RiskIDs      []int           `json:"riskIDs,omitempty"`
}

type UpdateRiskInput struct {
	ID                  int      `json:"id"`
	Name                string   `json:"name"`
	Description         string   `json:"description"`
	CategoryIDs         []string `json:"categoryIDs"`
	SpecificImpact      string   `json:"specificImpact"`
	LikelihoodID        string   `json:"likelihoodID"`
	ImpactID            string   `json:"impactID"`
	ResponseTeamIDs     []string `json:"responseTeamIDs"`
	AssigneeIDs         []string `json:"assigneeIDs"`
	DetectionIndicators string   `json:"detectionIndicators"`
}

type UpdateSlackSourceInput struct {
	ID          string   `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	ChannelIDs  []string `json:"channelIDs,omitempty"`
	Enabled     *bool    `json:"enabled,omitempty"`
}

type UpdateSourceInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
}

type ResponseStatus string

const (
	ResponseStatusBacklog    ResponseStatus = "BACKLOG"
	ResponseStatusTodo       ResponseStatus = "TODO"
	ResponseStatusInProgress ResponseStatus = "IN_PROGRESS"
	ResponseStatusBlocked    ResponseStatus = "BLOCKED"
	ResponseStatusCompleted  ResponseStatus = "COMPLETED"
	ResponseStatusAbandoned  ResponseStatus = "ABANDONED"
)

var AllResponseStatus = []ResponseStatus{
	ResponseStatusBacklog,
	ResponseStatusTodo,
	ResponseStatusInProgress,
	ResponseStatusBlocked,
	ResponseStatusCompleted,
	ResponseStatusAbandoned,
}

func (e ResponseStatus) IsValid() bool {
	switch e {
	case ResponseStatusBacklog, ResponseStatusTodo, ResponseStatusInProgress, ResponseStatusBlocked, ResponseStatusCompleted, ResponseStatusAbandoned:
		return true
	}
	return false
}

func (e ResponseStatus) String() string {
	return string(e)
}

func (e *ResponseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResponseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResponseStatus", str)
	}
	return nil
}

func (e ResponseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResponseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResponseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourceType string

const (
	SourceTypeNotionDb SourceType = "NOTION_DB"
	SourceTypeSLACk    SourceType = "SLACK"
)

var AllSourceType = []SourceType{
	SourceTypeNotionDb,
	SourceTypeSLACk,
}

func (e SourceType) IsValid() bool {
	switch e {
	case SourceTypeNotionDb, SourceTypeSLACk:
		return true
	}
	return false
}

func (e SourceType) String() string {
	return string(e)
}

func (e *SourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceType", str)
	}
	return nil
}

func (e SourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
