name: publish

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  TAG_NAME: hecatoncheires:${{ github.sha }}
  BUILD_VERSION: ${{ github.sha }}
  GITHUB_IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/hecatoncheires
  GITHUB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hecatoncheires:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Run cicd-sensor
        uses: cicd-sensor/cicd-sensor-action@6ee257338e68af2b279b321b3346fe5f385aa498 # v0.0.29

      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the tag or commit id
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_OR_COMMIT=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            echo "This is a tag: $TAG_OR_COMMIT"
          else
            TAG_OR_COMMIT=$(echo $GITHUB_SHA)
            echo "This is a commit SHA: $TAG_OR_COMMIT"
          fi
          echo "TAG_OR_COMMIT=$TAG_OR_COMMIT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: true
          tags: ${{ env.GITHUB_IMAGE_NAME }}
          build-args: |
            BUILD_VERSION=${{ steps.version.outputs.TAG_OR_COMMIT }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache,mode=max
          platforms: linux/amd64
